version: '3'

services:
  resource:
    image: repo.maresource.fr/groupe1cesi/resource:main
    container_name: resource
    ports:
      - "32589:3000"
    environment:
      VIRTUAL_HOST: "www.maresource.fr, maresource.fr"
      LETSENCRYPT_HOST: "www.maresource.fr, maresource.fr"
    networks:
      - nginx-proxy
    restart: unless-stopped

networks:
  nginx-proxy:
    external:
      name: nginx-proxy