import Nav from "../components/client/nav";

export const metadata = {
    title: 'Ressource',
    description : 'Generated by create next app'
}

export default function RootLayout ({children}){
    return (
        <html lang="fr">
            <body>
            <div>
                <Nav/>
                {children}
            </div>
            </body>
        </html>
    )
}